name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: osgeo/gdal:ubuntu-full-3.6.0

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install build deps
      shell: bash
      run: |
        apt-get update -y
        apt-get install build-essential curl pkg-config libclang-dev -y
        curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --profile minimal --default-toolchain none -y
        echo "${CARGO_HOME:-$HOME/.cargo}/bin" >> $GITHUB_PATH
    
    - name: Install stable
      run: |
        rustup install --no-self-update --profile minimal stable
        rustup component add rustfmt clippy    
    
    - name: Build
      run: cargo build --verbose
    
    - name: Run tests
      run: cargo test --verbose
